### PR TITLE
Fix to add scene release info when adding an NSP file

### PR DESCRIPTION
**Pull request by CameronVetter**
This does fix logic as well as making sure the scene info is used for NSP files as well.  Not 100% sure that all the fields available are being used, but its way better, and much more usable.

### CODE REVIEW

**Comment by CameronVetter** [comment]
Also added a column in the scene list to help identify if the item is in their collection

**Comment by gibaBR** [comment]
It raises an exception when I click on the list of scene releases.

**Comment by CameronVetter** [comment]
I fixed the exception on click bug, should be ready to merge

**Comment by gibaBR** [comment]
Take a look at this (dont forget to go to options->Visual):
https://mega.nz/#!WSAySAbD!AB0CX-lLkE4YYyimVtIzu9bq61lggh1_-8LNZYMESgM

What do you think of this?

**Comment by CameronVetter** [comment]
I'm not able to load it, I'm guessing the objectlistview files I have are a version mismatch...  I haven't had much luck unless I take all the files generated from the release build together

**Comment by gibaBR** [comment]
Ok, try this instead:
https://mega.nz/#!OCIgUKzI!1ZZix41e0DrH3TCS6UIGEOcDK1KBfce1OytALHSeAKk

**Comment by CameronVetter** [comment]
Yes, that seems like another way of providing the same information.  I'm good either way.  

I would suggest rethinking the highlight colors, deep green with black text is hard to read.  I would switch to a much lighter green...   

The other thing I would point out is that those colors are terrible if a person has colorblindness.  Take a look at this: https://usabilla.com/blog/how-to-design-for-color-blindness/  The image near the top of that article shows what a color blind person would see, and happens to have the three colors you chose in it.  (Far left is normal, three on the right are diff kinds of color blindness) I deal with this stuff in my day job and this impacts a lot of people, I'm guessing this tool has (or will have) a rather large audience, so it's probably worth adjusting for this.

Two options for fixing that, either include the column I suggested and stick to the same colors OR switch to a friendlier palette, see this article for suggestions. http://mkweb.bcgsc.ca/colorblind/

I'm glad to see you're going to run with the spirit of my idea!

**Comment by gibaBR** [comment]
Hey, you can choose the colours at the options screen.

Em dom, 2 de set de 2018 12:47, Cameron Vetter <notifications@github.com>
escreveu:

**Comment by CameronVetter** [comment]
Got it, I did just notice that the build you sent me does not map the fields correctly for eshop titles, which was some of the changes in this PR, specifically the scene id is always 0, but i'm guessing that means the rest of those fixes are missing too.

**Comment by gibaBR** [comment]
I've implemented in a different way. Thank you.

**Pull request closed without merging**
