### PR TITLE
Fix for Scene ID and other NSP info not being pulled from the scene l…

### PR DESCRIPTION
**Pull request by CameronVetter**
…ist and added to the xml database

This was in my previous PR, but discarded with everything else.  Current state of NSP without this is pretty broken

### CODE REVIEW

**Comment by CameronVetter** [comment]
Is there a reason you haven't merged this in?  It fixes a ton of broken stuff with NSP's

**Comment by gibaBR** [comment]
I'm sorry I didn't pay atention. Can you please explain what your code
fixes exactly? What is not working?

Thank you!

Em ter, 6 de nov de 2018 13:49, Cameron Vetter <notifications@github.com
escreveu:

**Comment by CameronVetter** [comment]
I just compared to your current mainline, and the issues got fixed with other checkins.  I'm closing this PR

**Comment by gibaBR** [comment]
Thank you, and sorry again.
---
Gilberto Júnior
http://raspberrybrasil.blogspot.com.br/
http://www.flickr.com/photos/gibajr/

**Pull request closed without merging**
